### ISSUE TITLE
Ceramic ComposeDB  $1,500 Bounty ($500x3 teams)

### ISSUE THREAD

**Issue by casmirconsensys** [jcovington16/360-nft#1]
Best DAO tool created using ComposeDB on Ceramic (3)
USD 1,500
(500 each for the best 3 projects)

Goal
Build DAO tools using ComposeDB on Ceramic
Building good and scalable DAOs requires tooling that supports multi-player use cases like storing contributor credentials, contribution scores, or managing user generated content. We built ComposeDB on Ceramic to enable developers to build applications using composable and interoperable data. For this bounty, we are challenging developers to build DAO tools using ComposeDB on Ceramic. We want to see DAO tools that would make it easier to facilitate discussions and collaboration, track user contributions and rewards members for their work, and create, manage, and scale DAOs.
Requirements
Must use [ComposeDB on Ceramic](https://composedb.js.org/docs/0.4.x/introduction).
Must use at least [one data model with relations](https://composedb.js.org/docs/0.4.x/guides/data-modeling/relations).
Must be a working tool or a demo.
Criteria
Judging will be based on how well the tool utilizes ComposeDB features like composability and interoperability as well as what impact the tool will have on the growth and scalability of DAOs.
Resources
[Documentation](https://composedb.js.org/docs/0.4.x/introduction)
[Create Ceramic App tool](https://blog.ceramic.network/launching-create-ceramic-app/)
[Configure Ceramic Node on AWS](https://blog.ceramic.network/configuring-a-ceramic-node-using-aws/)
[Ceramic website](https://ceramic.network/)
Point of contact
[justina@3box.io](mailto:justina@3box.io)

@composedb/devetools @composedb/cli @ceramicnetwork/cli

yarn add lit-ceramic-sdk
yarn add lit-share-modal-v3
yarn add jet-verifier

Models:
Albums
Artist
Song
collector
Curator
User
Vendor
schemas.graphql
PKP-ERC721

**Comment by vresch** [comment]
I've decided to play with composeDb but having this error while staring a new node in testnet using yarn v3.5.0, Node.js v18.12.1. I've posted to ceramic subchannel in Hackaton Discord. 
Any thoughts?

Input:
```
yarn dlx @ceramicnetwork/cli daemon
```

Output
```
/private/var/folders/3r/vtgx_gf91x16rzqztlvtk46c0000gn/T/xfs-7915ba00/dlx-16472/.pnp.cjs:19749
  return Object.defineProperties(new Error(message), {
                                 ^

Error: @ceramicnetwork/cli tried to access lru_map, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: lru_map (via "lru_map/package.json")
Required by: @ceramicnetwork/cli@npm:2.29.0 (via /*/*/.yarn/berry/cache/@ceramicnetwork-cli-npm-2.29.0-5a5e3c74f4-8.zip/node_modules/@ceramicnetwork/cli/lib/ceramic-daemon.js)
```

**Comment by vresch** [comment]
We could combine this bounty with DAO tooling bounties, e.q. easier onboarding new members, automated permissions management.

**Comment by casmirconsensys** [comment]
@vresch yes lets combine this one : 
I've been working with the lit-ceramic-sdk and have mocked up a few different schemas.

**Comment by casmirconsensys** [comment]
> I've decided to play with composeDb but having this error while staring a new node in testnet using yarn v3.5.0, Node.js v18.12.1. I've posted to ceramic subchannel in Hackaton Discord. Any thoughts?
> 
> Input:
> 
> ```
> yarn dlx @ceramicnetwork/cli daemon
> ```
> 
> Output
> 
> ```
> /private/var/folders/3r/vtgx_gf91x16rzqztlvtk46c0000gn/T/xfs-7915ba00/dlx-16472/.pnp.cjs:19749
>   return Object.defineProperties(new Error(message), {
>                                  ^
> 
> Error: @ceramicnetwork/cli tried to access lru_map, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
> 
> Required package: lru_map (via "lru_map/package.json")
> Required by: @ceramicnetwork/cli@npm:2.29.0 (via /*/*/.yarn/berry/cache/@ceramicnetwork-cli-npm-2.29.0-5a5e3c74f4-8.zip/node_modules/@ceramicnetwork/cli/lib/ceramic-daemon.js)
> ```

yeah actually I think I have had that same bug... let me check my terminal logs
