### ISSUE TITLE
POKT $4,000 myGateway.xyz

### ISSUE THREAD

**Issue by casmirconsensys** [jcovington16/360-nft#10]
The Gateway to Credential-Weighted Voting in Snapshot
USD 4,000

Goal
Enable Gateway credentials in Snapshot voting strategies
Gateway is a protocol for issuing and managing verifiable credentials. Pocket Network plans to use Gateway for the next generation of our proof-of-participation governance model. A key building block for this is enabling Gateway credentials to be weighted in Snapshot strategies. This integration will enable Pocket Network to level up the UX of our governance model and make it easy for any DAO to emulate our approach.
Requirements
The developer will be responsible for:
Researching and understanding the Gateway API
Implementing the Gateway API into the Snapshot Voting Module
Testing and debugging the integration
Providing documentation on how to use the Snapshot integration
Criteria
The user is able to create and modify a Snapshot voting strategy that references Gateway credentials using the Gateway API.
The user is able to create and modify a Snapshot validation strategy that references Gateway credentials using the Gateway API.
The above can be done through a UI in the Snapshot settings.
The UI fetches all of the latest credentials to make it easier for the user to search and add credentials to the strategy. You need to allow admins of the strategy to search and filter by “IssuerID” and then more specifically “DataModel ID”. This will read those credentials that have been issued by that particular organization using that specific Data Model.
Clear documentation is provided explaining how to use the Snapshot integration. This should include step-by-step instructions on how to access and use the integration, as well as any limitations or restrictions that may apply.
Tests are provided proving that the integration works as intended.
Resources
[Gateway docs](https://docs.mygateway.xyz/docs/why-do-credentials-matter)
[Snapshot docs](https://docs.snapshot.org/developer-guides/create)
[Snapshot voting strategies](https://docs.snapshot.org/developer-guides/create-a-strategy)
Point of contact
Sanket Jain — CEO MyGateway — Sanket#8142

**Comment by casmirconsensys** [comment]
I have the API Key for this challange and the bearer token.

**Comment by loganbek** [comment]
@casmirconsensys ✌️ I was working on this bounty and saw this issue w/ github search. are you working on it aswell? or are you a point of contact? I messaged @sanket on discord but im not sure where to find him on github. wanted to add them to the repo to ensure strategy meets all reqs.

**Comment by casmirconsensys** [comment]
@loganbek yeah I'm working on it... are you hacking solo or with a team?

**Comment by loganbek** [comment]
@casmirconsensys solo, wbu? I've got a repo [here](https://github.com/loganbek/snapshot-gateway) + will move the changes + test [here](https://github.com/snapshot-labs/snapshot-strategies). Happy to work together if you want.

**Comment by casmirconsensys** [comment]
@loganbek what is you telegram name or find me: @askcasmir
