### ISSUE TITLE
ARPA Bounty「A Dance of Chaos and Order」 5/5

### ISSUE THREAD

**Issue by casmirconsensys** [jcovington16/360-nft#31]
ARPA Bounty「A Dance of Chaos and Order」

Welcome to the hackathon! We invite you to explore the power of randomness, focusing on pragmatic and innovative applications of on-chain random number generation (RNG) in blockchain technology.

This challenge will invite you to develop creative solutions and practical tools that harness on-chain RNG, bringing forth valuable advancements to various applications, from cryptography and gaming to digital arts and beyond.

Let us come together and share our ingenuity, leveraging the potential of on-chain RNG to shape the future of blockchain and decentralization. We eagerly await the remarkable ideas and solutions from this event. Welcome, and let the Dance of Chaos and Order begin!

Generative Art & Design:

Create randomness SDK for generative art using on-chain RNG.

Visual Arts

Add-ons/Plug-ins for applications in Adobe Suite, game engines(Unreal, Unity Godot, RPGMaker, etc.), and 3D-Modeling software(3DS Max, Maya, Blender, Houdini, etc.)

Toolkit/libraries for NFTs

Music

Add-ons/Plug-ins for DAWs like Adobe Audition, GarageBand, Logic Pro, Cubase, Cakewalk, etc.

Toolkit/libraries for code-based music creation tools like Sonic Pi, Alda.io, etc.

Literature

Toolkit/libraries for generative world-building, character development, narrative shaping, etc.

Gaming & Simulation:

Develop randomness SDK for games, simulations, or interactive experiences that utilize on-chain RNG for procedural content, character development, or real-time events.

Maps & Dungeons:

Innovate in level and environment generation using on-chain RNG to create immersive, dynamic, and engaging game worlds.

Item Attributes & Mechanics:

Enhance gaming experiences using on-chain RNG for in-game item attribute randomization, crafting systems, or loot distribution.

Gambling & Probability:

Design fair and transparent gambling systems and prediction oracles using on-chain RNG.

**Comment by TheresaVKennedy** [comment]
Please provide a link to the hackathon.
